---

tomcat_config_server_tomcat_users:
  manager-gui:
    catalina_base: /home/kundea/tomcat
    owner: kundea
    group: kundea
    element: role
    element_name: manager-gui

  user1:
    catalina_base: /home/kundea/tomcat
    owner: kundea
    group: kundea
    element: user
    element_name: user1
    password: blahh
# this is an array
    roles:
      - manager_gui